apiVersion: v1
kind: Service
metadata:
    name: emmanuelkoechloanwebapp
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
      targetport: 8080
    selector:
        app: emmanuelkoechloanwebapp
